
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/shopdb

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT secret & expiry (example values – change the secret!)
app.jwt.secret=this_app_is_being_developed_by_@debmalya1101_Lives_in_$$$###
app.jwt.expiration-ms=86400000

# Security debug (optional)
logging.level.org.springframework.security=INFO

